--------------------------------------------------------
--  파일이 생성됨 - 일요일-8월-29-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "DEMO"."TEST" 
   (	"NO" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"TEL" VARCHAR2(200 BYTE), 
	"BIRTH" DATE, 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEMO"."TEST"."NO" IS '회원번호';
   COMMENT ON COLUMN "DEMO"."TEST"."ID" IS '아이디';
   COMMENT ON COLUMN "DEMO"."TEST"."TEL" IS '연락처';
   COMMENT ON COLUMN "DEMO"."TEST"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "DEMO"."TEST"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "DEMO"."TEST"."NAME" IS 'name';
REM INSERTING into DEMO.TEST
SET DEFINE OFF;
Insert into DEMO.TEST (NO,ID,TEL,BIRTH,ADDRESS,NAME) values (1,'user','010-1111-1234',to_date('93/01/01','RR/MM/DD'),'경상북도 영천시 문외동','권수민');
Insert into DEMO.TEST (NO,ID,TEL,BIRTH,ADDRESS,NAME) values (35,'ever4412','010-1111-1234',to_date('21/08/03','RR/MM/DD'),'경상북도 영천시 문외동','뚜민');
Insert into DEMO.TEST (NO,ID,TEL,BIRTH,ADDRESS,NAME) values (41,'test','010-000',to_date('21/08/03','RR/MM/DD'),'경상북도 읍천리 읍천군','테스트222');
Insert into DEMO.TEST (NO,ID,TEL,BIRTH,ADDRESS,NAME) values (33,'hong','010-1234-5678',to_date('21/08/11','RR/MM/DD'),'대구광역시 달서구 홍길동','홍길동');
Insert into DEMO.TEST (NO,ID,TEL,BIRTH,ADDRESS,NAME) values (34,'sasha','010-1234-5678',to_date('21/06/03','RR/MM/DD'),'서울특별시 강남대로 75길','샤샤');
--------------------------------------------------------
--  DDL for Index TEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."TEST_PK" ON "DEMO"."TEST" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "DEMO"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMO"."TEST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."TEST" MODIFY ("NO" NOT NULL ENABLE);
